### ISSUE TITLE
Chat completion

### ISSUE THREAD

**Issue by vicperdana** [rohit-lakhanpal/ai-hackathon-starter-kit#15]
@rohit-lakhanpal I assume completion is not ready as yet as I am getting an error running it.  I can also see that you have noted this as future roadmap item.  Since it doesn't work, perhaps should remove the UI component for completion or just note it README under KNOWN LIMITATION?  Just a suggestion.

**Comment by rohit-lakhanpal** [comment]
Added functionality within this PR https://github.com/rohit-lakhanpal/ai-hackathon-starter-kit/pull/12
